### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by darkkain** [nickbalestra/hero#1]
We (aka only me) totaly need filetype icons, colored. Smth like this:
![quvc6xx](https://cloud.githubusercontent.com/assets/4064924/6861620/3c010b8a-d44a-11e4-8d3e-d35c2a2d87f1.png)

**Comment by nickbalestra** [comment]
No need to add this as a feature, you can simply add those on a user level:
- create folder named "Theme - Hero" inside Packages/User
- in there add an empty file named "Hero Dark.sublime-theme" and make sure it contains:

``` javascript
[
    {
        "class": "icon_file_type",
        "content_margin": [8,8]
    }
]
```

In the same folder copy https://github.com/pryley/soda-theme and you should be ready to go.
For more info: https://www.sublimetext.com/forum/viewtopic.php?f=2&t=15971&start=20

**Comment by kevinchevallier** [comment]
Works, but you'll only need the "icons" folder in the "Theme - Hero" folder. Note that the icons are pretty bad at 16px, difficult to read. But that's another subject. I'm trying to get better ones.

**Comment by cvergne** [comment]
@kevinchevallier icons from Seti_UI are working pretty well with Hero theme ;)

**Comment by abdulmanan7** [comment]
i like ,hero own style .

**Comment by BaymaxCao923** [comment]
Really works. In the beginning, I was in the wrong folder. The right 'User' folder should be at _**Preferences->Browse Packages...**_ (Such a fool I am XD) I think maybe somebody could make the same mistake as I do, just leave this comment to help them. :-)

**Comment by stockbrot** [comment]
I used the icons from "Dark Material" theme, they work really well with this theme.

Here is my "Theme - Hero.sublime-theme":
```
[
	{
		"class": "icon_file_type",
		// layer0.texture is filled in by code with the relevant icon name
		"layer0.opacity": 0.6,
		"content_margin": [9, 9]
	},
	{
		"class": "icon_file_type",
		"parents": [{"class": "tree_row", "attributes": ["selected"]}],
		"layer0.opacity": 1,
		"content_margin": [9, 9]
	},
]
```

[https://packagecontrol.io/packages/Theme%20-%20Dark%20Material]Dark Material Theme
