### ISSUE TITLE
Loud filename and selection color

### ISSUE THREAD

**Issue by cryzed** [nickbalestra/hero#4]
Hey, I really like your theme! I'm not sure if it was a deliberate stylistic choice, but would you consider toning down the really aggressive white color for the filenames in the sidebar and blue color for menu selections? I feel it would match the overall feel and dark colors of the theme better then, although I am aware that it's an entirely subjective choice.

**Comment by nickbalestra** [comment]
Thanks for the feedback. I almost never use the sidebar and didn't notice it. I'll try to make a little sidebar sprint in the future so I can improve it. 

I quite like what has been done on the sidebar for the primer theme, https://github.com/karelvuong/st-primer, probably taking some inspiration form that once I'll start refactoring. 

If you have other good examples, please share.

**Comment by cryzed** [comment]
Yes, the sidebar in those screenshots looks really great! I was originally also planning to suggest adding sidebar icons, but I didn't want to spam your bugtracker with personal requests on how you "should" design your theme. There's also [this](https://github.com/mrmartineau/SetiUI-Icons-Sublime) which I discovered yesterday when looking around, but I didn't manage to actually make use of it even when following the instructions (I think certain settings in Hero's sublime-theme file prevent it from working properly currently). Thanks for considering my suggestions!

**Comment by nickbalestra** [comment]
Thanks for the link to the icon Pack, looks good. Ive tried to play around with the sidebar a little bit and this is what I have sofar, what ya think?
![screen shot 2015-03-28 at 18 18 51](https://cloud.githubusercontent.com/assets/389705/6882011/f72d47de-d576-11e4-9c34-12a0e6e42fc4.png)

**Comment by cryzed** [comment]
Much nicer selection color, is this one also used for the command palette menu? Regarding the icons, I'm not sure about their bright colors yet and how well it mixes with the rest of the theme's color scheme, but I only see the bright yellow JavaScript icons in your screenshot. Could you maybe open [this](https://github.com/mrmartineau/SetiUI-Icons-Sublime/tree/master/%2Bres/file-types) directory in your sidebar and showcase the rest too? If the transition between the mellow colors and the bright icons is too jarring, you might want to consider either darkening their colors or turning them monochrome and transparent (kind of like how Heroku [does it](http://i.imgur.com/f4DKmwp.png) too), although I fear the latter might end up looking boring.

I hope I don't seem too presumptuous, and these are just suggestion by someone who isn't very artistically inclined, so take it with a grain, or two, of salt. But yes, I like the changes portrayed in the screenshot, and would definitely prefer it over the current version.

**Comment by nickbalestra** [comment]
Done with the sidebar, no file icons added, but are support so follow the instruction found on many place to add them. Theme should update soon via packageControl.

**Comment by cryzed** [comment]
Awesome, thank you!
